export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const FETCHING_DATA = 'FETCHING_DATA';
export const FETCH_COUNTRY = 'FETCH_COUNTRY';
export const POST_DATA = 'POST_DATA';
export const GET_DATA = 'GET_DATA';

export const NO_CONNECTION = 'NO_CONNECTION';

export const CREATE_GROUP = 'CREATE_GROUP';
export const DISPLAY_GROUP = 'DISPLAY_GROUP';
export const DELETE_GROUP = 'DELETE_GROUP';
export const UPDATE_GROUP = 'UPDATE_GROUP'

export const DISPLAY_MEMBER = 'DISPLAY_MEMBER';
export const DISPLAY_HOME_MEMBER = 'DISPLAY_HOME_MEMBER';
export const DISPLAY_HOME_MARKER = 'DISPLAY_HOME_MARKER';
export const DISPLAY_GROUP_MEMBER = 'DISPLAY_GROUP_MEMBER';
export const INVITE_MEMBER = 'INVITE_MEMBER';
export const GET_MEMBER = 'INVITE_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const GENERATE_INVITATIONCODE = 'GENERATE_INVITATIONCODE';
export const GET_INVITATIONCODE = 'GET_INVITATIONCODE';
export const GET_COUNTRIES = 'GET_COUNTRIES';
export const CLEAR_HOME_MEMBERS = 'CLEAR_HOME_MEMBERS';
export const GET_MEMBERGROUP = 'GET_MEMBERGROUP';
export const GET_MEMBERNOTIFICATION = 'GET_MEMBERNOTIFICATION';





export const SIGNIN_USER = 'SIGNIN_USER';
export const REGISTRATION_USER = 'REGISTRATION_USER';
export const GET_PROFILE = 'GET_PROFILE';



export const DISPLAY_LOCATION = 'DISPLAY_LOCATION';
export const DISPLAY_LOCATION_MAP = 'DISPLAY_LOCATION_MAP';
export const DISPLAY_LOCATION_TRACK = 'DISPLAY_LOCATION_TRACK';
export const DISPLAY_LOCATION_LIST = 'DISPLAY_LOCATION_LIST';
export const SAVE_LOCATION_OFFLINE = 'SAVE_LOCATION_OFFLINE';
export const SAVE_LOCATION_ONLINE = 'SAVE_LOCATION_ONLINE';
export const DISPLAY_PLACES = 'DISPLAY_PLACES';
export const GET_PLACE_ALERT = 'GET_PLACE_ALERT';
export const GET_LOCATIONDETAILS = 'GET_LOCATIONDETAILS';



export const CONNECTION_STATE = 'CONNECTION_STATE';
export const GET_CONNECTION = 'GET_CONNECTION';


